# Tensor

In [1]:
import torch

In [2]:
print(torch.__version__)

2.9.0+cu130


## Tensor Basic

In [3]:
# 텐서의 기본 선언
# Basic tensor declaration
# torch.FloatTensor와 동일
# Equivalent to torch.FloatTensor
# x = torch.Tensor(행, 열)
# x = torch.Tensor(rows, cols)
x = torch.Tensor(2, 3)
print(x)

tensor([[1.3719e-19, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 5.0938e-14, 4.1613e-41]])


In [4]:
# 텐서의 정보 확인
# Check tensor info
print("Tensor Type : ", type(x))
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size()) # x.shape

Tensor Type :  <class 'torch.Tensor'>
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


## Tensor with characteristics

In [5]:
# 0으로 채워진 텐서 선언
# Declare a tensor filled with zeros
x = torch.zeros(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [6]:
x = torch.zeros(2,3, dtype=torch.int32)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
Tensor Type :  torch.IntTensor
Tensor Size :  torch.Size([2, 3])


In [7]:
# 1로 채워진 텐서 선언
# Declare a tensor filled with ones
x = torch.ones(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [8]:
# 0과 1 사이 랜덤값으로 채워진 텐서 선언
# Declare a tensor filled with random values in [0, 1)
x = torch.rand(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0.3555, 0.5237, 0.6470],
        [0.8603, 0.7155, 0.4416]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [9]:
# 평균 0, 분산 1의 정규분포에서 샘플링한 값으로 채운 텐서 선언
# Declare a tensor filled with samples from N(0, 1)
x = torch.randn(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[ 1.5800,  0.3164,  0.4320],
        [ 0.7223, -0.2610, -0.2610]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [10]:
# 정방행렬 형태의 텐서 선언 (단위행렬)
# Declare a square (identity) tensor
x = torch.eye(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 0., 0.],
        [0., 1., 0.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [11]:
# 0부터 2까지 0.5 간격으로 증가하는 텐서 선언
# Declare a tensor from 0 to 2 with step 0.5
x = torch.arange(0, 2, step=0.5)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([0.0000, 0.5000, 1.0000, 1.5000])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([4])


In [12]:
# 직접 값을 입력하여 선언
# Declare with explicit values
x = torch.Tensor([[1,2,3],[1,2,3]])
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [13]:
# 32-bit 부동소수점
# 32-bit floating point
x = torch.FloatTensor(2,3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[5.1582e-17, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [14]:
# 32-bit 부호 있는 정수
# 32-bit signed integer
x = torch.IntTensor(2,3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[611138742,         0,         0],
        [        0,        32,         0]], dtype=torch.int32)
Tensor Type :  torch.IntTensor
Tensor Size :  torch.Size([2, 3])


## Tensor and Numpy

In [15]:
import numpy as np

In [16]:
# NumPy 형식의 배열
# A NumPy array
x = np.array([[1,2,3],[1,2,3]])
print(x, type(x))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


In [17]:
# NumPy를 텐서로 변환
# Convert NumPy array to tensor
x = torch.from_numpy(x) # x = torch.Tensor(x)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1, 2, 3],
        [1, 2, 3]])
Tensor Type :  torch.LongTensor
Tensor Size :  torch.Size([2, 3])


In [18]:
# 텐서를 NumPy로 변환
# Convert tensor to NumPy array
x = x.numpy()
print(x, type(x))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


## Tensor Slicing

In [19]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [20]:
# 모든 원소 출력
# Print all elements
x[:, :]

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [21]:
# 2행부터 끝까지 출력
# Print from row 2 onward
x[1:, :]

tensor([[ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [22]:
# 2열부터 끝까지 출력
# Print from column 2 onward
x[:, 1:]

tensor([[ 2.,  3.,  4.],
        [ 6.,  7.,  8.],
        [10., 11., 12.]])

In [23]:
# 2행, 2~3열 출력
# Print row 2, columns 2 to 3
x[1:, 1:3]

tensor([[ 6.,  7.],
        [10., 11.]])

In [24]:
# 1행 출력
# Print row 1
x[0, :]

tensor([1., 2., 3., 4.])

In [25]:
# x를 1행씩 잘라 배열로 저장
# Split x by rows into a list
x_rows = torch.split(x, split_size_or_sections=1, dim=0)
print(x_rows)

(tensor([[1., 2., 3., 4.]]), tensor([[5., 6., 7., 8.]]), tensor([[ 9., 10., 11., 12.]]))


In [26]:
# x를 2열씩 잘라 배열로 저장
# Split x into chunks of 2 columns
x_cols = torch.split(x, split_size_or_sections=2, dim=1)
print(x_cols)

(tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]]), tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]))


In [27]:
# 위와 동일한 결과
# Same result as above
torch.chunk(x, chunks=2, dim=1)

(tensor([[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]]),
 tensor([[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]))

In [28]:
# x_cols의 첫번째 배열에서 특정 부분만 추출
# Extract a slice from the first array in x_cols
torch.masked_select(x_cols[0], torch.BoolTensor([[0,1],[1,0],[0,1]]).bool())

tensor([ 2.,  5., 10.])

## Tensor Merging

In [29]:
# x_rows를 행 방향으로 이어 붙이기
# Concatenate x_rows along rows
torch.cat(x_rows, dim=0)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [30]:
# x_rows를 열 방향으로 이어 붙이기
# Concatenate x_rows along columns
torch.cat(x_rows, dim=1)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [31]:
# x_cols를 쌓아올리기
# Stack x_cols
x_new = torch.stack(x_cols, dim=0)
print(x_new)

tensor([[[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]],

        [[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]])


## Tensor Reshaping

In [32]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [33]:
# 4행 3열로 reshape
# Reshape into 4 rows × 3 columns
x.view(4, 3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [34]:
# 2열로 reshape
# Reshape into 2 columns
x.view(-1, 2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [35]:
x.view(2, 1, -1)

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])

In [36]:
# 크기가 1인 차원 제거 (squeeze)
# Squeeze out singleton dimension
x.view(2, 1, -1).squeeze()

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

In [37]:
# dim=1 위치에 새 차원 추가
# Insert a new dim at position 1
x.view(2, 1, -1).squeeze().unsqueeze(dim=1)

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])

## Tensor Calculation

In [38]:
x = torch.Tensor([[1,2,3],[4,5,6]])
y = torch.Tensor([[1,1,1],[2,2,2]])
print("x :", x)
print("y :", y)

x : tensor([[1., 2., 3.],
        [4., 5., 6.]])
y : tensor([[1., 1., 1.],
        [2., 2., 2.]])


In [39]:
# x와 y의 합
# Sum of x and y
z = torch.add(x, y)
print("z :", z)
print("x+y :", x+y)

z : tensor([[2., 3., 4.],
        [6., 7., 8.]])
x+y : tensor([[2., 3., 4.],
        [6., 7., 8.]])


In [40]:
# x의 모든 원소에서 2를 뺌
# Subtract 2 from every element of x
print(x - 2)

# x의 모든 원소에 2를 곱함
# Multiply every element of x by 2
print(2*x)

tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [41]:
# x와 y의 원소별 곱
# Element-wise multiplication of x and y
z = torch.mul(x, y)
print("z :", z)
print("x*y :", x*y)

z : tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])
x*y : tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])


In [42]:
# x의 각 원소를 제곱
# Element-wise square of x
z = torch.pow(x, 2)
print("z :", z)
print("x**2 :", x**2)

z : tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
x**2 : tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


In [43]:
# x의 각 원소에 log
# Element-wise log of x
z = torch.log(x)
print("z :", z)
print("x.log() :", x.log())

z : tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
x.log() : tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])


In [44]:
# x의 각 원소에 제곱근
# Element-wise sqrt of x
z = torch.sqrt(x)
print("z :", z)
print("x.sqrt() :", x.sqrt())

z : tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])
x.sqrt() : tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])


In [45]:
# x의 각 원소에 나머지 연산
# Element-wise modulo on x
z = x % 2
print(z)

tensor([[1., 0., 1.],
        [0., 1., 0.]])


In [46]:
# x의 절댓값
# Absolute value of x
z = torch.abs(x)
print("z :", z)
print("x.abs() :", x.abs())

z : tensor([[1., 2., 3.],
        [4., 5., 6.]])
x.abs() : tensor([[1., 2., 3.],
        [4., 5., 6.]])


## Tensor Casting

In [47]:
x = torch.Tensor([[1,2,3],[4,5,6]])
y = torch.Tensor([[1,1,1],[2,2,2]])
print("x :", x)
print("y :", y)

x : tensor([[1., 2., 3.],
        [4., 5., 6.]])
y : tensor([[1., 1., 1.],
        [2., 2., 2.]])


In [48]:
x.type(torch.DoubleTensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [49]:
x.double()

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [50]:
x.type(torch.IntTensor)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [51]:
x.int()

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

## Tensor Statistic

In [52]:
x = torch.Tensor([[-1,2,-3],[4,-5,6]])
print(x)

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])


In [53]:
print("x의 합 :", x.sum())
print("x의 최대값 :", x.max())
print("x의 최소값 :", x.min())
print("x의 분산 :", x.var())

x의 합 : tensor(3.)
x의 최대값 : tensor(6.)
x의 최소값 : tensor(-5.)
x의 분산 : tensor(17.9000)


In [54]:
# 스칼라 텐서
# Scalar Tensor
x.sum().size()

torch.Size([])

In [55]:
# item() 활용
# Using .item() to get a Python scalar
print("x의 합 :", x.sum().item())
print("x의 최대값 :", x.max().item())
print("x의 최소값 :", x.min().item())
print("x의 분산 :", x.var().item())

x의 합 : 3.0
x의 최대값 : 6.0
x의 최소값 : -5.0
x의 분산 : 17.899999618530273


In [56]:
# 행(dim=0) 기준 열별 최댓값
# Max of each column along dim=0
value, index = x.max(dim=0)
value, index

(tensor([4., 2., 6.]), tensor([1, 0, 1]))

In [57]:
# 열(dim=1) 기준 행별 최댓값
# Max of each row along dim=1
value, index = x.max(dim=1)
value, index

# torch.max(x, dim=1)과 동일한 결과
# Same result as torch.max(x, dim=1)
# 이는 추후에 계속 등장하므로 매우 중요!
# This pattern is very important — it will keep appearing later

(tensor([2., 6.]), tensor([1, 2]))

In [58]:
# 열(dim=1) 기준으로 각 행을 정렬
# Sort each row along dim=1 (columns)
value, index = x.sort(dim=1)
value

tensor([[-3., -1.,  2.],
        [-5.,  4.,  6.]])

## Tensor *_like function

In [59]:
x = torch.Tensor([[-1,2,-3],[4,-5,6]])
print(x)

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])


In [60]:
y = torch.zeros_like(x)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [61]:
y = torch.ones_like(x)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [62]:
y = torch.rand_like(x)
print(y)

tensor([[0.0619, 0.6373, 0.1913],
        [0.2020, 0.7327, 0.3720]])


## Tensor for GPU

In [63]:
x = torch.Tensor([[1,2,3],[1,2,3]])
print(x)

tensor([[1., 2., 3.],
        [1., 2., 3.]])


In [64]:
# cuda 확인
# Check CUDA availability
print("현재 Cuda 사용 가능한 Device 개수 :", torch.cuda.device_count())
print("현재 Cuda 사용 가능 여부 :", torch.cuda.is_available())
print("현재 사용 중인 Cuda Device :", torch.cuda.current_device())
print("현재 Cuda Device 이름 :", torch.cuda.get_device_name(0))
print("현재 Cuda Device의 사용 가능한 메모리 :", torch.cuda.max_memory_allocated(device=0), "bytes")
print("현재 Cuda Device의 사용 중인 메모리 :", torch.cuda.memory_allocated(device=0), "bytes")

현재 Cuda 사용 가능한 Device 개수 : 1
현재 Cuda 사용 가능 여부 : True
현재 사용 중인 Cuda Device : 0
현재 Cuda Device 이름 : NVIDIA GeForce RTX 5090
현재 Cuda Device의 사용 가능한 메모리 : 0 bytes
현재 Cuda Device의 사용 중인 메모리 : 0 bytes


In [65]:
# cuda 세팅
# CUDA setup
torch.cuda.set_device(0)

In [66]:
# CPU 텐서를 GPU로 전환
# Move CPU tensor to GPU
gpu_x = x.cuda()
print(gpu_x)
print("Tensor Type : ", gpu_x.type())
print("Tensor Size : ", gpu_x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]], device='cuda:0')
Tensor Type :  torch.cuda.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [67]:
# CPU 텐서를 GPU로 전환 (방법 2)
# Move CPU tensor to GPU (alternative)
device = torch.device("cuda")
gpu_x = x.to(device)
print(gpu_x)
print("Tensor Type : ", gpu_x.type())
print("Tensor Size : ", gpu_x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]], device='cuda:0')
Tensor Type :  torch.cuda.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [68]:
# GPU 텐서를 CPU로 전환
# Move GPU tensor to CPU
x = gpu_x.cpu()
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [69]:
# GPU 텐서를 CPU로 전환 (방법 2)
# Move GPU tensor to CPU (alternative)
device = torch.device("cpu")
x = gpu_x.to(device)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [70]:
# GPU 텐서와 CPU 텐서의 연산
# Mixing GPU tensor with CPU tensor
gpu_x + x

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

## Tensor Broadcasting / 텐서 브로드캐스팅

브로드캐스팅은 shape이 다른 텐서를 자동으로 확장해 element-wise 연산을 가능하게 합니다.
Broadcasting automatically expands tensors with different shapes for element-wise operations.

In [71]:
# 브로드캐스팅 예제: (2, 3) + (3,)
# Broadcasting example: (2, 3) + (3,)
a = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])
b = torch.tensor([10., 20., 30.])

print("a.shape:", a.shape)
print("b.shape:", b.shape)
print("a + b =\n", a + b)  # b가 행 방향으로 확장됨 / b is expanded across rows

# 브로드캐스팅 예제: (2, 3) + (2, 1)
# Broadcasting example: (2, 3) + (2, 1)
c = torch.tensor([[100.],
                  [200.]])

print("c.shape:", c.shape)
print("a + c =\n", a + c)  # c가 열 방향으로 확장됨 / c is expanded across columns

a.shape: torch.Size([2, 3])
b.shape: torch.Size([3])
a + b =
 tensor([[11., 22., 33.],
        [14., 25., 36.]])
c.shape: torch.Size([2, 1])
a + c =
 tensor([[101., 102., 103.],
        [204., 205., 206.]])
