# Backprop by Autograd

## Autograd Basics

In [1]:
import torch

In [2]:
x = torch.ones(1)
x.requires_grad

False

In [3]:
y = torch.ones(1)
y.requires_grad

False

In [4]:
z = x + y

In [5]:
z.requires_grad

False

In [6]:
x.requires_grad_()
x.requires_grad

True

In [7]:
z = x + y

In [8]:
z.requires_grad

True

## Backward

In [9]:
y = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32, requires_grad=True)
y

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [10]:
z = 2*y + 1
z

tensor([[3., 5.],
        [7., 9.]], grad_fn=<AddBackward0>)

In [11]:
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)

print("")

print("y.grad :", y.grad)
print("z.grad :", z.grad)

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)

y.requires_grad : True
z.requires_grad : True

y.grad : None
z.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward0 object at 0x79b01574b370>


/tmp/ipykernel_24464/3957125995.py:7: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  print("z.grad :", z.grad)


In [12]:
gz = z.grad_fn
print("z.grad_fn :", gz)
print("Where is z.grad_fn?", id(gz))
print("Where is z.grad_fn in hex?", hex(id(gz)))

z.grad_fn : <AddBackward0 object at 0x79b01574b2b0>
Where is z.grad_fn? 133797181174448
Where is z.grad_fn in hex? 0x79b01574b2b0


In [13]:
# next_functions로 다음 backward 함수를 파악할 수 있음
# next_functions reveals the next backward op in the graph
z.grad_fn.next_functions

((<MulBackward0 at 0x79b01574ac50>, 0), (None, 0))

In [14]:
# grad는 스칼라 출력에 대해서만 암묵적으로 생성됨
# grad can be implicitly created only for scalar outputs
z.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [15]:
out = z.sum()
out

tensor(24., grad_fn=<SumBackward0>)

In [16]:
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)
print("out.requires_grad :", out.requires_grad)

print("")

print("y.grad :", y.grad)
print("z.grad :", z.grad)
print("out.grad :", out.grad)

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)
print("out.grad_fn :", out.grad_fn)

y.requires_grad : True
z.requires_grad : True
out.requires_grad : True

y.grad : None
z.grad : None
out.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward0 object at 0x79b01574b2b0>
out.grad_fn : <SumBackward0 object at 0x79b01568ef20>


/tmp/ipykernel_24464/925780261.py:8: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  print("z.grad :", z.grad)
/tmp/ipykernel_24464/925780261.py:9: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/p

In [17]:
out.backward()

In [18]:
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)
print("out.requires_grad :", out.requires_grad)

print("")

print("y.grad :", y.grad)
print("z.grad :", z.grad)
print("out.grad :", out.grad)

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)
print("out.grad_fn :", out.grad_fn)

y.requires_grad : True
z.requires_grad : True
out.requires_grad : True

y.grad : tensor([[2., 2.],
        [2., 2.]])
z.grad : None
out.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward0 object at 0x79b01574b2b0>
out.grad_fn : <SumBackward0 object at 0x79b0156900d0>


/tmp/ipykernel_24464/925780261.py:8: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  print("z.grad :", z.grad)
/tmp/ipykernel_24464/925780261.py:9: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/p

In [19]:
# 기본적으로 gradient는 leaf 변수에만 보존됨. 비-leaf 변수는
# By default, gradients are only retained for leaf variables. Non-leaf vars
# 비-leaf 변수의 gradient는 메모리 절약을 위해 보존되지 않음
# Non-leaf gradients are not retained — by design, to save memory
print("y == leaf? : ", y.is_leaf)
print("z == leaf? : ", z.is_leaf)

y == leaf? :  True
z == leaf? :  False


## Backward Twice

In [20]:
y = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32, requires_grad=True)
z = 2*y + 1
out = z.sum()
out.backward()
out.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [21]:
y = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32, requires_grad=True)
z = 2*y + 1
out = z.sum()
out.backward(retain_graph=True)
out.backward()

In [22]:
y.grad

tensor([[4., 4.],
        [4., 4.]])

## Backward with Multiple Gradients

In [3]:
y = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32, requires_grad=True)
z1 = 2*y + 1
z2 = 3*y + 1
out = z1.sum() + z2.sum()
out.backward()

In [4]:
y.grad

tensor([[5., 5.],
        [5., 5.]])

## .detach() vs .data

In [23]:
# 그래프 위에 있는 변수는 바로 numpy로 변환할 수 없음
# A variable on the graph cannot be converted to numpy directly
z.numpy()

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [24]:
# 따라서 .detach() 또는 .data 중 하나를 사용해야 함
# So we must use either .detach() or .data
z.detach().numpy()

array([[3., 5.],
       [7., 9.]], dtype=float32)

In [25]:
# 따라서 .detach() 또는 .data 중 하나를 사용해야 함
# So we must use either .detach() or .data
z.data.numpy()

array([[3., 5.],
       [7., 9.]], dtype=float32)

.detach()된 tensor는 requires_grad=False 이지만 원본 storage를 공유함

A .detach() tensor has requires_grad=False but still shares underlying storage

In [26]:
a = torch.tensor([1,2,3.], requires_grad = True)
b = a.exp()

# c는 b를 그래프에서 떼어낸 것으로 requires_grad=False
# c is detached from b's graph; requires_grad becomes False
# 그러나 원본 데이터는 공유됨
# But the underlying storage is shared
c = b.detach()
c.zero_()

tensor([0., 0., 0.])

In [27]:
# c를 0으로 만들었으므로, 데이터를 공유하는 b도 0이 됨
# c was zeroed and shares storage with b, so b is also zeroed
b

tensor([0., 0., 0.], grad_fn=<ExpBackward0>)

In [28]:
# exp 함수는 자기 자신의 출력값이 역전파에 필요
# exp() requires its own output during backprop
# 그러나 원본 데이터가 수정되었으므로 에러가 나는 것이 맞음
# But since the underlying data was modified, raising an error is the correct behavior
b.sum().backward()

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [3]], which is output 0 of ExpBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

In [29]:
# backward가 진행되지 않았으므로 a.grad는 없어야 함
# Since backward did not run, a.grad must be None
a.grad

.data 사용은 autograd 안전장치를 우회해 잘못된 gradient를 만들 수 있음

Using .data can bypass autograd safety checks and lead to incorrect gradients

In [30]:
a = torch.tensor([1,2,3.], requires_grad = True)
b = a.exp()

# c를 0으로 초기화
# Zero-out c
c = b.data
c.zero_()

tensor([0., 0., 0.])

In [31]:
# 마찬가지로 b도 0으로 초기화됨
# Likewise, b is also zeroed
b

tensor([0., 0., 0.], grad_fn=<ExpBackward0>)

In [32]:
# inplace 변경이 있었음에도 에러가 나지 않음 (비정상 동작)
# In-place modification did NOT raise an error (incorrect behavior)
b.sum().backward()

In [33]:
# 잘못된 결과
# Incorrect result
a.grad

tensor([0., 0., 0.])

안전하게 복사하려면 detach().clone()을 사용

Use detach().clone() for a safe copied tensor

In [34]:
a = torch.tensor([1,2,3.], requires_grad = True)
b = a.exp()

# c를 0으로 초기화
# Zero-out c
c = b.detach().clone()
c.zero_()

tensor([0., 0., 0.])

In [35]:
b

tensor([ 2.7183,  7.3891, 20.0855], grad_fn=<ExpBackward0>)